"""TurboQuant PyTorch baseline plus K/V-separated research extensions."""

from turboquant.analysis import summarize_layer_thresholds, summarize_trial_metrics
from turboquant.allocation import ChannelBitAllocation
from turboquant.gguf_profiles import (
    build_hypura_bridge_config,
    build_hypura_serve_command,
    GGUF_HYPURA_COMPAT_AUTO,
    GGUF_HYPURA_COMPAT_OFF,
    GGUF_TURBOQUANT_EXACT_PROFILE,
    HypuraTurboQuantBridgeConfig,
    TurboQuantGGUFManifest,
    TurboQuantGGUFProfile,
    build_paper_gguf_profile,
    build_so8_triality_vector_gguf_profile,
    infer_gguf_attention_head_dim,
    infer_gguf_block_count,
    package_turboquant_gguf,
    read_hypura_gguf_bridge_config,
    read_turboquant_gguf_manifest,
    resolve_hypura_compatibility_bridge,
)
from turboquant.kv_codec import KVCodec, KVCodecConfig
from turboquant.paper_baseline import (
    PAPER_BASELINE_MODES,
    PaperMSEConfig,
    PaperMixedBitPolicy,
    PaperProdConfig,
    PaperTurboQuantMSE,
    PaperTurboQuantProd,
    evaluate_paper_attention_grid,
)
from turboquant.reporting import summarize_metric_trials
from turboquant.research_extension import (
    KeyResearchConfig,
    ProtectedValueCodec,
    TRIALITY_PROXY_VIEWS,
    TrialityProxyMSE,
    TrialityProxyProd,
    V_ABLATION_MODES,
    ValueResearchConfig,
)
from turboquant.schema import (
    PAPER_SCHEMA_KIND,
    RESEARCH_SCHEMA_KIND,
    build_paper_turboquant_config,
    build_research_turboquant_config,
    build_turboquant_gguf_contract,
    build_uniform_turboquant_gguf_contract,
    read_turboquant_config,
    validate_turboquant_gguf_contract,
    validate_paper_turboquant_config,
    validate_research_turboquant_config,
    write_turboquant_config,
)
from turboquant.triality_contract import (
    TRIALITY_ALLOWED_MODES,
    TRIALITY_GGUF_NAMESPACE,
    TRIALITY_GGUF_PAYLOAD_FORMAT,
    TRIALITY_GGUF_SCHEMA_VERSION,
    TRIALITY_PROXY_PARETO_LEGACY_ALIAS,
    TRIALITY_PROXY_PARETO_MODE,
    TrialityModeSpec,
    build_triality_metadata,
    build_triality_payload,
    payload_json_dumps,
    resolve_triality_mode_spec,
    validate_triality_metadata,
    validate_triality_payload,
)
from turboquant.turboquant_mse import TurboQuantMSE
from turboquant.turboquant_prod import TurboQuantProd
from turboquant.types import TurboQuantMSEConfig, TurboQuantProdConfig

__all__ = [
    "ChannelBitAllocation",
    "build_hypura_bridge_config",
    "build_hypura_serve_command",
    "GGUF_HYPURA_COMPAT_AUTO",
    "GGUF_HYPURA_COMPAT_OFF",
    "GGUF_TURBOQUANT_EXACT_PROFILE",
    "HypuraTurboQuantBridgeConfig",
    "KeyResearchConfig",
    "KVCodec",
    "KVCodecConfig",
    "PAPER_BASELINE_MODES",
    "PAPER_SCHEMA_KIND",
    "PaperMSEConfig",
    "PaperMixedBitPolicy",
    "PaperProdConfig",
    "PaperTurboQuantMSE",
    "PaperTurboQuantProd",
    "ProtectedValueCodec",
    "TRIALITY_PROXY_VIEWS",
    "TurboQuantGGUFManifest",
    "TurboQuantGGUFProfile",
    "TRIALITY_ALLOWED_MODES",
    "TRIALITY_GGUF_NAMESPACE",
    "TRIALITY_GGUF_PAYLOAD_FORMAT",
    "TRIALITY_GGUF_SCHEMA_VERSION",
    "TRIALITY_PROXY_PARETO_LEGACY_ALIAS",
    "TRIALITY_PROXY_PARETO_MODE",
    "TrialityProxyMSE",
    "TrialityProxyProd",
    "TrialityModeSpec",
    "RESEARCH_SCHEMA_KIND",
    "V_ABLATION_MODES",
    "ValueResearchConfig",
    "build_paper_gguf_profile",
    "build_paper_turboquant_config",
    "build_research_turboquant_config",
    "build_so8_triality_vector_gguf_profile",
    "build_turboquant_gguf_contract",
    "build_uniform_turboquant_gguf_contract",
    "build_triality_metadata",
    "build_triality_payload",
    "evaluate_paper_attention_grid",
    "infer_gguf_attention_head_dim",
    "infer_gguf_block_count",
    "package_turboquant_gguf",
    "payload_json_dumps",
    "read_hypura_gguf_bridge_config",
    "read_turboquant_config",
    "read_turboquant_gguf_manifest",
    "resolve_triality_mode_spec",
    "resolve_hypura_compatibility_bridge",
    "summarize_layer_thresholds",
    "summarize_metric_trials",
    "summarize_trial_metrics",
    "TurboQuantMSE",
    "TurboQuantMSEConfig",
    "TurboQuantProd",
    "TurboQuantProdConfig",
    "validate_triality_metadata",
    "validate_triality_payload",
    "validate_turboquant_gguf_contract",
    "validate_paper_turboquant_config",
    "validate_research_turboquant_config",
    "write_turboquant_config",
]
