"""K/V-separated research extensions built on top of the paper baseline."""

from turboquant.research_extension.evaluation import (
    V_ABLATION_MODES,
    captured_v_ablation_rows,
    compute_value_sensitivity_rows,
    evaluate_value_protection_grid,
    filter_v_ablation_rows,
    synthetic_v_ablation_rows,
)
from turboquant.research_extension.multiscreen_kv import (
    build_mipe_factor,
    compute_k_relevance,
    expand_relevance_bitwidths_to_key_shape,
    multiscreen_relevance_topk_indices,
    normalize_unit,
    trim_and_square,
)
from turboquant.research_extension.k_triality import (
    DEFAULT_PRODUCTION_TRIALITY_ROTATION_DIR,
    MULTISCREEN_TRIALITY_VECTOR_MODE,
    PRODUCTION_K_TURBOQUANT_MODE,
    PRODUCTION_K_TURBOQUANT_VIEW,
    ROTATION_COMPARE_MODES,
    TRIALITY_SELECTOR_MODE,
    TRIALITY_MODE_BY_VIEW,
    bit_setting_sort_key,
    build_best_per_layer_selector,
    compute_friedman_rotation_mode_statistics,
    compute_pairwise_wilcoxon_rotation_modes,
    compute_triality_selector_statistics,
    compute_triality_statistics,
    evaluate_multiscreen_triality_vector_row,
    evaluate_triality_proxy_captured,
    fit_triality_proxy_rotations,
    load_triality_proxy_rotations,
    save_triality_proxy_rotations,
    triality_mode_name,
)
from turboquant.research_extension.triality_proxy import (
    TRIALITY_PROXY_VIEWS,
    TrialityProxyMSE,
    TrialityProxyProd,
    apply_blockwise_view,
    apply_triality_proxy_view,
    get_triality_proxy_adapters,
    invert_triality_proxy_view,
    triality_proxy_adapter,
)
from turboquant.research_extension.types import KeyResearchConfig, ValueResearchConfig
from turboquant.value_codec import ProtectedValueCodec

__all__ = [
    "build_mipe_factor",
    "compute_k_relevance",
    "expand_relevance_bitwidths_to_key_shape",
    "multiscreen_relevance_topk_indices",
    "normalize_unit",
    "trim_and_square",
    "KeyResearchConfig",
    "ProtectedValueCodec",
    "DEFAULT_PRODUCTION_TRIALITY_ROTATION_DIR",
    "MULTISCREEN_TRIALITY_VECTOR_MODE",
    "PRODUCTION_K_TURBOQUANT_MODE",
    "PRODUCTION_K_TURBOQUANT_VIEW",
    "TRIALITY_MODE_BY_VIEW",
    "TRIALITY_SELECTOR_MODE",
    "TRIALITY_PROXY_VIEWS",
    "bit_setting_sort_key",
    "TrialityProxyMSE",
    "TrialityProxyProd",
    "V_ABLATION_MODES",
    "ValueResearchConfig",
    "apply_blockwise_view",
    "apply_triality_proxy_view",
    "captured_v_ablation_rows",
    "compute_value_sensitivity_rows",
    "ROTATION_COMPARE_MODES",
    "build_best_per_layer_selector",
    "compute_friedman_rotation_mode_statistics",
    "compute_pairwise_wilcoxon_rotation_modes",
    "compute_triality_selector_statistics",
    "compute_triality_statistics",
    "evaluate_value_protection_grid",
    "evaluate_multiscreen_triality_vector_row",
    "evaluate_triality_proxy_captured",
    "filter_v_ablation_rows",
    "fit_triality_proxy_rotations",
    "get_triality_proxy_adapters",
    "invert_triality_proxy_view",
    "load_triality_proxy_rotations",
    "save_triality_proxy_rotations",
    "synthetic_v_ablation_rows",
    "triality_mode_name",
    "triality_proxy_adapter",
]
